services:
  mysql:
    image: mysql:8.0
    container_name: auth_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - auth_network
    command: --default-authentication-plugin=mysql_native_password

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_nextjs_app
    restart: always
    environment:
      - DATABASE_URL=mysql://root:password@mysql:3306/auth_db
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_EXPIRES_IN=86400
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - auth_network
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - ./docker-entrypoint.sh:/app/docker-entrypoint.sh
      - ./wait-for-it.sh:/app/wait-for-it.sh

networks:
  auth_network:
    driver: bridge

volumes:
  mysql_data: